/*
 * TCC RTTI Runtime API
 * 
 * This header provides the runtime API for accessing RTTI information
 * generated by TCC with __attribute__((annotate("reflect", "TypeName")))
 */

#ifndef TCC_RTTI_RUNTIME_H
#define TCC_RTTI_RUNTIME_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Field flags */
#define TCC_RTTI_FIELD_IS_PTR      (1 << 0)
#define TCC_RTTI_FIELD_IS_ARRAY    (1 << 1)
#define TCC_RTTI_FIELD_IS_BITFIELD (1 << 2)

/* Runtime field information */
typedef struct tcc_rtti_field {
    const char *name;         /* Field name */
    int offset;               /* Field offset in struct */
    int type_id;              /* Type ID of the field */
    int flags;                /* Flags (is_ptr, is_array, is_bitfield) */
    int bit_offset;           /* Bit offset (for bitfields) */
    int bit_size;             /* Bit size (for bitfields) */
    int array_size;           /* Array size (if array, 0 otherwise) */
    struct tcc_rtti_type *type_info; /* Pointer to nested type info (if struct) */
} tcc_rtti_field_t;

/* Runtime type information */
typedef struct tcc_rtti_type {
    const char *name;         /* Type name */
    int size;                 /* Struct size */
    int align;                /* Alignment requirement */
    int field_count;          /* Number of fields */
    uint32_t type_hash;       /* Type hash for fast comparison */
    int type_id;              /* Unique type ID */
    tcc_rtti_field_t *fields; /* Array of field information */
} tcc_rtti_type_t;

/* RTTI section header (found at the beginning of .tcc_rtti section) */
typedef struct tcc_rtti_header {
    uint32_t magic;           /* Magic number: "TCC1" */
    uint32_t version;         /* Version number */
    uint32_t count;           /* Number of RTTI entries */
    uint32_t reserved;        /* Reserved */
} tcc_rtti_header_t;

#define TCC_RTTI_MAGIC   0x31434354  /* "TCC1" in little-endian */
#define TCC_RTTI_VERSION 1

/*
 * Get RTTI information by type name
 * 
 * Parameters:
 *   name - The type name specified in __attribute__((annotate("reflect", "name")))
 * 
 * Returns:
 *   Pointer to tcc_rtti_type_t if found, NULL otherwise
 */
const tcc_rtti_type_t *tcc_rtti_get(const char *name);

/*
 * Get RTTI information by type ID
 * 
 * Parameters:
 *   type_id - The unique type ID
 * 
 * Returns:
 *   Pointer to tcc_rtti_type_t if found, NULL otherwise
 */
const tcc_rtti_type_t *tcc_rtti_get_by_id(int type_id);

/*
 * Get RTTI information by type hash
 * 
 * Parameters:
 *   hash - The type hash
 * 
 * Returns:
 *   Pointer to tcc_rtti_type_t if found, NULL otherwise
 */
const tcc_rtti_type_t *tcc_rtti_get_by_hash(uint32_t hash);

/*
 * Get field information by name
 * 
 * Parameters:
 *   type - The type information
 *   field_name - The field name to find
 * 
 * Returns:
 *   Pointer to tcc_rtti_field_t if found, NULL otherwise
 */
const tcc_rtti_field_t *tcc_rtti_get_field(const tcc_rtti_type_t *type, const char *field_name);

/*
 * Get field offset by name (convenience function)
 * 
 * Parameters:
 *   type - The type information
 *   field_name - The field name to find
 * 
 * Returns:
 *   Field offset if found, -1 otherwise
 */
int tcc_rtti_get_field_offset(const tcc_rtti_type_t *type, const char *field_name);

/*
 * Get pointer to field value in a struct instance
 * 
 * Parameters:
 *   instance - Pointer to struct instance
 *   type - The type information
 *   field_name - The field name
 * 
 * Returns:
 *   Pointer to the field value, NULL if not found
 */
void *tcc_rtti_get_field_ptr(void *instance, const tcc_rtti_type_t *type, const char *field_name);

/*
 * Print RTTI information (for debugging)
 * 
 * Parameters:
 *   type - The type information to print
 */
void tcc_rtti_print(const tcc_rtti_type_t *type);

/*
 * Get the number of registered types
 * 
 * Returns:
 *   Number of registered types
 */
int tcc_rtti_get_count(void);

/*
 * Iterate over all registered types
 * 
 * Parameters:
 *   index - Index of the type (0 to count-1)
 * 
 * Returns:
 *   Pointer to tcc_rtti_type_t at the given index, NULL if out of range
 */
const tcc_rtti_type_t *tcc_rtti_get_at(int index);

#ifdef __cplusplus
}
#endif

#endif /* TCC_RTTI_RUNTIME_H */