/*
 * TCC RTTI Runtime Library
 * 
 * This file implements the runtime API for accessing RTTI information.
 * 
 * The RTTI data is generated by the compiler and stored in a global
 * array that can be accessed at runtime.
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>

/* Include the runtime API header */
#include "../include/tcc_rtti_runtime.h"

/*
 * The RTTI table is generated by the compiler.
 * It's declared as a weak symbol so programs without RTTI still work.
 */
extern const tcc_rtti_type_t *__tcc_rtti_table[];
extern const int __tcc_rtti_count;

/* Weak declarations for programs without RTTI */
__attribute__((weak)) const tcc_rtti_type_t *__tcc_rtti_table[1] = { NULL };
__attribute__((weak)) const int __tcc_rtti_count = 0;

/* Parsed RTTI data */
static int g_rtti_initialized = 0;
static int g_rtti_count = 0;
static const tcc_rtti_type_t **g_rtti_types = NULL;

/* Ensure RTTI is initialized */
static void ensure_initialized(void)
{
    if (g_rtti_initialized) {
        return;
    }
    
    g_rtti_count = __tcc_rtti_count;
    g_rtti_types = (const tcc_rtti_type_t **)__tcc_rtti_table;
    g_rtti_initialized = 1;
}

/* Get RTTI by name */
const tcc_rtti_type_t *tcc_rtti_get(const char *name)
{
    ensure_initialized();
    
    if (!name || !g_rtti_types) {
        return NULL;
    }
    
    for (int i = 0; i < g_rtti_count; i++) {
        if (g_rtti_types[i]->name && strcmp(g_rtti_types[i]->name, name) == 0) {
            return g_rtti_types[i];
        }
    }
    
    return NULL;
}

/* Get RTTI by type ID */
const tcc_rtti_type_t *tcc_rtti_get_by_id(int type_id)
{
    ensure_initialized();
    
    if (!g_rtti_types) {
        return NULL;
    }
    
    for (int i = 0; i < g_rtti_count; i++) {
        if (g_rtti_types[i]->type_id == type_id) {
            return g_rtti_types[i];
        }
    }
    
    return NULL;
}

/* Get RTTI by hash */
const tcc_rtti_type_t *tcc_rtti_get_by_hash(uint32_t hash)
{
    ensure_initialized();
    
    if (!g_rtti_types) {
        return NULL;
    }
    
    for (int i = 0; i < g_rtti_count; i++) {
        if (g_rtti_types[i]->type_hash == hash) {
            return g_rtti_types[i];
        }
    }
    
    return NULL;
}

/* Get field by name */
const tcc_rtti_field_t *tcc_rtti_get_field(const tcc_rtti_type_t *type, const char *field_name)
{
    if (!type || !field_name || !type->fields) {
        return NULL;
    }
    
    for (int i = 0; i < type->field_count; i++) {
        if (type->fields[i].name && strcmp(type->fields[i].name, field_name) == 0) {
            return &type->fields[i];
        }
    }
    
    return NULL;
}

/* Get field offset */
int tcc_rtti_get_field_offset(const tcc_rtti_type_t *type, const char *field_name)
{
    const tcc_rtti_field_t *field = tcc_rtti_get_field(type, field_name);
    return field ? field->offset : -1;
}

/* Get field pointer */
void *tcc_rtti_get_field_ptr(void *instance, const tcc_rtti_type_t *type, const char *field_name)
{
    if (!instance || !type) {
        return NULL;
    }
    
    int offset = tcc_rtti_get_field_offset(type, field_name);
    if (offset < 0) {
        return NULL;
    }
    
    return (char *)instance + offset;
}

/* Print RTTI info */
void tcc_rtti_print(const tcc_rtti_type_t *type)
{
    if (!type) {
        printf("RTTI: NULL\n");
        return;
    }
    
    printf("RTTI Type Info:\n");
    printf("  Name: %s\n", type->name ? type->name : "(anonymous)");
    printf("  Type ID: %d\n", type->type_id);
    printf("  Size: %d\n", type->size);
    printf("  Align: %d\n", type->align);
    printf("  Hash: 0x%08x\n", type->type_hash);
    printf("  Field Count: %d\n", type->field_count);
    
    if (type->fields) {
        for (int i = 0; i < type->field_count; i++) {
            const tcc_rtti_field_t *f = &type->fields[i];
            printf("    Field %d: %s\n", i, f->name ? f->name : "(anonymous)");
            printf("      Type ID: %d\n", f->type_id);
            printf("      Offset: %d\n", f->offset);
            if (f->flags & TCC_RTTI_FIELD_IS_BITFIELD) {
                printf("      Bitfield: offset=%d, size=%d\n",
                       f->bit_offset, f->bit_size);
            }
            if (f->flags & TCC_RTTI_FIELD_IS_ARRAY) {
                printf("      Array size: %d\n", f->array_size);
            }
        }
    }
}

/* Get count */
int tcc_rtti_get_count(void)
{
    ensure_initialized();
    return g_rtti_count;
}

/* Get at index */
const tcc_rtti_type_t *tcc_rtti_get_at(int index)
{
    ensure_initialized();
    
    if (index < 0 || index >= g_rtti_count || !g_rtti_types) {
        return NULL;
    }
    
    return g_rtti_types[index];
}
